# 일래스틱 빈스톡은 기본적으로 애플리케이션이 5000port를 사용한다고 생각한다.
server:
  port: 5000
  
# mysql 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
   #url: jdbc:mysql://localhost:3306/excitingamusement_boot?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
   #DB는 ESB가 만들어준다. app을 실행하면서 이 값을 지정해 줄수 있다. 
    url: jdbc:<db_type>://<host>:<port>/<db_name>?allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
   #username: root
   #password: rpass
    username: ${rds.username}
    password: ${rds.password}
#spring.datasource.url: jdbc:mysql://192.168.0.9:3306/excitingamusement_boot?serverTimezone=UTC&characterEncoding=UTF-8

# hibernate 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
      logging.level.org.hibernate.type.descriptor.sql: trace

# MVC 및 파일 업로드 설정
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload:
      directory: file:/C:/static/uploads/

# Oauth2.0 github 설정
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.4abea673861f0e51
            clientSecret: 559473762f895df05f107107aafd370f4ef81e5a
            redirectUri: "{baseUrl}/login/authGit/{registrationId}"
            scope: "user:email,read:user"
        provider:
          github:
            authorizationUri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user